# Advanced python 2022 Spring Exam


Shunyu Wu
21-119-631

In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

### 2. Working with numerial data

In [15]:
# 2a
arr_1 = np.array([4, 9, 0, 6, 2])
for i in range(len(arr_1)):
    if arr_1[i] == arr_1_sorted[-2]:
        print(i)

3


In [16]:
# 2b
arr_2 = np.arange(12).reshape(4,3)

In [21]:
print(np.mean(arr_2.T, axis=0))

[ 1.  4.  7. 10.]


In [24]:
# 2c
arr_3 = np.ones((9, 3)) 
arr_3_a = np.ones((1, 3)) 
arr_3_b = np.ones((3, 1))
display(arr_3, arr_3_a, arr_3_b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[1., 1., 1.]])

array([[1.],
       [1.],
       [1.]])

In [26]:
# arr_3+arr_3_a works, because arr_3_a can be broadcasted from shape(1,3) to shape(9,3), then they match and add
arr_3+arr_3_a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [33]:
# arr_3+arr_3_b cannot be performed because arr_3_b is of shape (3, 1) cannot be automatically broadcast to match (9,3) 
# the solution would be to use (:, np.newaxis) then it becomes (3,1,1) and add result is of shape (3,9,3)
arr_3 + arr_3_b[:, np.newaxis]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [40]:
# 2d
arr_4 = np.arange(50, 100).reshape(5,10) 
arr_4_a = [[62, 63], 
           [72, 73]] # 1 point 
arr_4_b = [[62, 65, 68] ,
           [82, 85, 88]] # 1 point

In [41]:
arr_4

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
arr_4_a_sl = arr_4[1:3, 2:4]
display(arr_4_a_sl)
arr_4_a_sl == arr_4_a

array([[62, 63],
       [72, 73]])

array([[ True,  True],
       [ True,  True]])

In [49]:
arr_4_b_sl = arr_4[1::2, 2::3]
display(arr_4_b_sl)
arr_4_b_sl == arr_4_b

array([[62, 65, 68],
       [82, 85, 88]])

array([[ True,  True,  True],
       [ True,  True,  True]])

# 3 DataFrames


In [66]:
# 3a
df = pd.read_csv('./Resources/SBB.csv')

In [68]:
# 3b
from datetime import datetime
df['Arrival'] = pd.to_datetime(df['Arrival'])
df['Arrival_predicted'] = pd.to_datetime(df['Arrival_predicted'])
df['Departure'] = pd.to_datetime(df['Departure'])

In [69]:
# 3c
df['delay'] = (df['Arrival'] - df['Arrival_predicted']).dt.total_seconds()

In [85]:
# 3d
df_bern = df[df['Stop'] == 'Bern']
bern_delay_percent = len(df_bern[df_bern['delay'] > 60]) / len(df[df['Stop'] == 'Bern'])
print('Bern delay percent: {:2.2%}'.format(bern_delay_percent))

df_lau = df[df['Stop'] == 'Lausanne']
lau_delay_percent = len(df_lau[df_lau['delay'] > 60]) / len(df[df['Stop'] == 'Lausanne'])
print('Lausanne delay percent: {:2.2%}'.format(lau_delay_percent))

df_basel = df[df['Stop'] == 'Basel SBB']
basel_delay_percent = len(df_basel[df_basel['delay'] > 60]) / len(df[df['Stop'] == 'Basel SBB'])
print('Basel delay percent: {:2.2%}'.format(basel_delay_percent))

Bern delay percent: 1.56%
Lausanne delay percent: 9.37%
Basel delay percent: 4.78%


In [105]:
# 3e
line_delay = df.groupby('Line')['delay'].mean()
print('Greatest average delay line: ', line_delay.idxmax())
print('Lowest average delay line: ', line_delay.idxmin())

Greatest average delay line:  IR37
Lowest average delay line:  ICE


# 4 Plotting

In [6]:
# 4a
df = pd.read_csv('./Resources/station_users.csv')

In [107]:
df

Station    2013    2014    2015    2016    2017    2018    2019    2020  \
0     Luzern  160000  157000  159000  163000  164000  167000  167000  105000   
1  Basel SBB  134000  135000  134000  135000  133000  134000  136000   92000   
2       Bern  306000  305000  313000  318000  324000  326000  330000  228000   
3   Lausanne  139000  140000  143000  149000  148000  145000  152000   97000   
4  Zurich HB  429000  437000  437000  439000  438000  443000  461000  295000   

     2021  
0  102000  
1   96000  
2  229000  
3  103000  
4  286000

In [ ]:
# 4b

plt.show()

# 5 python knowledge

In [113]:
# 5a
def ex_5a():
    names_1 = ['Blake', 'Adam', 'Anders', 'Jillian'] 
    names_2 = names_1 
    names_2[1] = 'Karl' 
    print(names_1)
    
ex_5a()

['Blake', 'Karl', 'Anders', 'Jillian']


In [ ]:
# 'Blake', 'Karl', 'Anders', 'Jillian'] will be printed becasue names_2 and names_1 point to the same position.
# and Karl is changed in names_2[1] so as in names_1

In [ ]:
# 5b
def ex_5b():
    try:
        names = ['Blake', 'Adam', 'Anders', 'Jillian'] 
        update_index = int(input('Index to update > ')) 
        update_value = input('New name to add > ') 
        names[update_index] = update_value
        assert update_index < len(names)
    except:
        print("Index must be within range!")
